export const ADD_TRACKER = 'ADD_TRACKER';
export const STOP_TRACKER = 'STOP_TRACKER';
export const RESUME_TRACKER = 'RESUME_TRACKER';
export const DELETE_TRACKER = 'DELETE_TRACKER';
export const SAVE_TIME_TRACKER = 'SAVE_TIME_TRACKER';
